### ISSUE TITLE
Swift 版本存在Bug

### ISSUE THREAD

**Issue by lnjpzyc** [amap-demo/iOS-multiroute-display#1]
MultiRoutePlanViewController.swift文件的386行代码，数组的遍历存在问题，应该将原来的

for index in 1..<(oriCoordinateArray.count-1) {

改为

for index in 1..<(oriCoordinateArray.count) {

否则的话，少一次循环，PolyLine画不上去。

**Comment by roylly** [comment]
火眼金睛，👍，已经修复。谢谢
